# Generated by Django 2.2.8 on 2021-03-09 18:02

from django.db import migrations, models
import olpkhoidong1.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KhoiDong1Question',
            fields=[
                ('questionID', models.IntegerField(primary_key=True, serialize=False, verbose_name='Câu hỏi số')),
                ('questionText', models.TextField(blank=True, verbose_name='Nội dung câu hỏi')),
                ('answer', models.CharField(max_length=256, verbose_name='Đáp án')),
                ('file', models.FileField(blank=True, upload_to=olpkhoidong1.models.questionDirectoryPath, verbose_name='File đính kèm')),
                ('fileType', models.CharField(blank=True, choices=[('sound', 'Âm thanh'), ('video', 'Video'), ('image', 'Hình ảnh')], max_length=10, verbose_name='Loại file')),
            ],
        ),
    ]
